---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-golang-fedora
    image: fedora:35

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

verifier:
  name: testinfra
  directory: ../default/tests
