---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-golang-fedora
    image: fedora:31
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: fedora

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
