---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-golang-opensuse
    image: opensuse/leap:15.3

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

verifier:
  name: testinfra
  directory: ../default/tests
