---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-golang-ubuntu-max-go-eol
    image: ubuntu:20.04

provisioner:
  name: ansible
  config_options:
    defaults:
      inject_facts_as_vars: false

verifier:
  name: testinfra
