---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-golang-ubuntu-max-go-eol
    image: ubuntu:18.04

provisioner:
  name: ansible

verifier:
  name: testinfra
