---
- name: create go sdk installation directory
  become: true
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    path: '{{ golang_install_dir }}'

- name: install unarchive dependencies (zypper)
  become: true
  zypper:
    name:
      - gzip
      - tar
    state: present
  when: ansible_pkg_mgr == 'zypper'

- name: install go sdk
  become: true
  unarchive:
    src: "{{ golang_download_dir }}/{{ golang_archive_filename }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    dest: "{{ golang_install_dir }}"
    owner: root
    group: root
    creates: "{{ golang_install_dir }}/bin"

# Set Go language SDK environment variables
- name: make sure /etc/profile.d exists
  become: true
  file:
    path: /etc/profile.d
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: configure go path environment variables
  become: true
  template:
    src: golang.sh.j2
    dest: /etc/profile.d/golang.sh
    owner: root
    group: root
    mode: "u=rw,go=r"
