---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-golang-centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: centos-8
verifier:
  name: ansible
