---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-golang-ubuntu-arm32
    image: ubuntu:22.04
    platform: linux/arm/v7

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

verifier:
  name: testinfra
  directory: ../default/tests
