---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-golang-debian-8
    image: debian:8
    dockerfile: ../default/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: debian-8
verifier:
  name: ansible
