---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-golang-ubuntu-trusty
    image: ubuntu:14.04

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-trusty

verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
