---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-golang-debian-wheezy
    image: debian:7
  - name: ansible-role-golang-debian-jessie
    image: debian:8
  - name: ansible-role-golang-ubuntu-trusty
    image: ubuntu:14.04
  - name: ansible-role-golang-ubuntu-xenial
    image: ubuntu:16.04
  - name: ansible-role-golang-centos-6
    image: centos:6
  - name: ansible-role-golang-centos-7
    image: centos:7

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
