---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-golang-centos-7
    image: centos:7
    dockerfile: ../default/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: centos-7
verifier:
  name: ansible
