---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ansible-role-golang-ubuntu-18.04
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-18.04
verifier:
  name: ansible
