---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-golang-centos-max
    image: centos:7
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: centos-max

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
